# Generated by Django 2.2.4 on 2022-04-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='discription',
            field=models.TextField(default='Nice'),
        ),
    ]
