# Generated by Django 2.2.4 on 2022-04-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=45)),
                ('year', models.DateTimeField()),
                ('price', models.FloatField(max_length=45)),
                ('maker', models.CharField(max_length=45)),
                ('desc', models.TextField(max_length=100)),
                ('seller', models.ManyToManyField(related_name='cars', to='exam.User')),
            ],
        ),
    ]
