# Generated by Django 2.2.4 on 2022-04-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='seller',
        ),
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='exam.User'),
            preserve_default=False,
        ),
    ]
